'services:' 
'  - type: web' 
'    name: zero-mumu-backend' 
'    runtime: python' 
'    repo: https://github.com/rxmi-dev/zero-mumu-tax.git' 
'    branch: main' 
'    buildCommand: pip install -r requirements.txt' 
'    startCommand: gunicorn run:app' 
'    rootDir: backend' 
